// Daily self-talk — the affirmation shown at the top of the client's home dashboard.
// 1,000 lines. ~60% are release/re-identity statements starting "I never" / "I no longer";
// ~40% are present-tense identity statements starting "I am" / "It's like me now".
// Themes: health, fitness, accountability. Picked once per day (stable all day, changes
// each morning) and spread across the whole pool so consecutive days aren't neighbors.

export const AFFIRMATIONS: string[] = [
  // ── I NEVER / I NO LONGER — showing up & not skipping ──
  "I never skip a workout just because I don't feel like it.",
  "I no longer wait to feel motivated before I move my body.",
  "I never let a busy day become a reason to do nothing.",
  "I no longer treat my workout as optional.",
  "I never negotiate with myself once the plan is set.",
  "I no longer hit snooze on the person I'm becoming.",
  "I never let a rough morning cancel my whole day.",
  "I no longer save my effort for Monday.",
  "I never talk myself out of showing up.",
  "I no longer need a perfect setup to get started.",
  "I never skip the days that count the most.",
  "I no longer let tiredness make my decisions for me.",
  "I never let one missed day turn into a missed week.",
  "I no longer wait for the 'right time' to begin.",
  "I never leave my workout to chance.",
  "I no longer let my mood decide whether I train.",
  "I never let a small excuse stop a big goal.",
  "I no longer disappear on myself when things get hard.",
  "I never skip movement just because no one is watching.",
  "I no longer let comfort win over commitment.",
  "I never let a full schedule crowd out my health.",
  "I no longer put everyone else's needs above my own body.",
  "I never let a late start become no start.",
  "I no longer break the promise I made to move today.",
  "I never let the couch talk me out of my plan.",
  "I no longer trade my workout for one more scroll.",
  "I never let weather or timing be my excuse.",
  "I no longer wait until I 'have more energy' to begin.",
  "I never skip the warm-up to my future self.",
  "I no longer let a slow start ruin a good day.",
  "I never treat consistency as a someday goal.",
  "I no longer let a hard week erase my progress.",
  "I never let one skipped session become my new normal.",
  "I no longer show up only when it's easy.",
  "I never let my calendar be an excuse to quit on me.",
  "I no longer wait to be inspired — I just begin.",
  "I never let 'I'll do it later' be my final answer.",
  "I no longer let a good excuse cost me a good day.",
  "I never leave my body waiting for a better mood.",
  "I no longer let the hardest ten minutes stop me.",

  // ── I NEVER / I NO LONGER — excuses ──
  "I no longer hide behind my excuses.",
  "I never let 'I'm too tired' be the end of the conversation.",
  "I no longer explain away the effort I owe myself.",
  "I never dress up an excuse as a reason.",
  "I no longer let 'I don't have time' decide my health.",
  "I never blame my schedule for my choices.",
  "I no longer let a good story keep me stuck.",
  "I never talk myself into staying the same.",
  "I no longer let 'tomorrow' carry today's work.",
  "I never let a convenient excuse win.",
  "I no longer trade my goals for a comfortable lie.",
  "I never let 'it's been a long day' undo my discipline.",
  "I no longer accept excuses I wouldn't accept from anyone else.",
  "I never let 'I'll start Monday' run my life.",
  "I no longer let small reasons block big change.",
  "I never justify quitting on myself.",
  "I no longer let 'just this once' become every time.",
  "I never let an off day become an off month.",
  "I no longer wait for conditions to be perfect.",
  "I never let 'I deserve a break' become a way to hide.",
  "I no longer make my excuses louder than my goals.",
  "I never let the easy way out set my standard.",
  "I no longer let 'I'll make up for it later' fool me.",
  "I never confuse being busy with being unable.",
  "I no longer let excuses do my thinking for me.",
  "I never let a reason to stop outweigh my reason to go.",
  "I no longer talk myself out of what I said I'd do.",
  "I never let one weak moment write the whole story.",
  "I no longer excuse the version of me I've outgrown.",
  "I never let my comfort zone make my choices.",

  // ── I NEVER / I NO LONGER — junk food, sugar & cravings ──
  "I no longer let cravings run my day.",
  "I never eat to escape my feelings.",
  "I no longer reward a hard day with food that hurts me.",
  "I never let sugar decide how I feel about myself.",
  "I no longer eat past full just because it tastes good.",
  "I never let a craving convince me it's a need.",
  "I no longer treat junk food as comfort.",
  "I never let the vending machine make my decisions.",
  "I no longer eat mindlessly in front of a screen.",
  "I never let stress send me to the pantry.",
  "I no longer let one treat turn into a whole binge.",
  "I never confuse a craving with real hunger.",
  "I no longer eat because I'm bored.",
  "I never let sweets have power over my willpower.",
  "I no longer use food to numb what I'd rather feel.",
  "I never let a bad mood raid the fridge.",
  "I no longer let processed food fill the space where peace belongs.",
  "I never let a craving outlast my goal.",
  "I no longer snack just to fill the silence.",
  "I never let sugar highs run my energy.",
  "I no longer eat to please everyone at the table.",
  "I never let 'I already messed up' justify eating more.",
  "I no longer keep eating after my body says enough.",
  "I never let a craving convince me it can't wait.",
  "I no longer let the drive-thru decide my dinner.",
  "I never trade my goals for a moment on my tongue.",
  "I no longer let emotional eating steer my week.",
  "I never let a hard day become a heavy plate.",
  "I no longer eat on autopilot.",
  "I never let 'just a bite' erase a good day.",
  "I no longer feed my stress instead of facing it.",
  "I never let cravings talk me out of the body I want.",
  "I no longer let late-night snacking undo my morning.",
  "I never treat sugar as a friend that's failing me.",
  "I no longer eat fast to outrun my feelings.",
  "I never let one indulgence become an identity.",
  "I no longer confuse fullness with satisfaction.",
  "I never let cravings win the argument.",
  "I no longer let the pantry set my mood.",
  "I never eat to fill a space that food can't fill.",
  "I no longer let sweet cravings quietly steal my progress.",
  "I never let a craving become a crisis.",
  "I no longer chase comfort in things that leave me heavier.",
  "I never let junk food masquerade as a reward.",
  "I no longer let my cravings out-vote my goals.",

  // ── I NEVER / I NO LONGER — quitting & all-or-nothing ──
  "I no longer quit the moment it gets uncomfortable.",
  "I never give up on myself halfway through.",
  "I no longer let one slip end the whole plan.",
  "I never abandon a goal because progress is slow.",
  "I no longer throw away a good week over one bad meal.",
  "I never let perfect be the enemy of done.",
  "I no longer restart from zero every time I stumble.",
  "I never let a setback become a stopping point.",
  "I no longer treat one mistake as a total failure.",
  "I never let discouragement have the final word.",
  "I no longer walk away when the results are still forming.",
  "I never let slow progress feel like no progress.",
  "I no longer quit right before it starts working.",
  "I never let an all-or-nothing mindset take everything.",
  "I no longer let a missed day cancel my streak of effort.",
  "I never surrender the goal to a bad afternoon.",
  "I no longer bail on myself when the plan gets boring.",
  "I never let frustration decide that I'm done.",
  "I no longer let a plateau convince me to stop.",
  "I never quit on the hard days that build me.",
  "I no longer let one off week undo six good ones.",
  "I never trade long-term wins for short-term relief.",
  "I no longer give up just because I can't see the finish yet.",
  "I never let doubt cash in my discipline.",
  "I no longer treat 'good enough' as a reason to quit.",
  "I never let a bad start ruin a strong finish.",
  "I no longer walk away from what I said mattered.",
  "I never let a rough patch become a permanent stop.",
  "I no longer confuse resting with quitting.",
  "I never let the middle of the journey end it.",
  "I no longer abandon my body when it needs me most.",
  "I never let one weak day define my whole week.",
  "I no longer quit because someone else did.",
  "I never let a hard rep be the reason I stop.",
  "I no longer let discouragement outlast my commitment.",
  "I never let 'this is taking forever' stop me.",
  "I no longer let a slow scale erase my effort.",
  "I never give my goals a deadline for giving up.",
  "I no longer let one bad workout end a good habit.",
  "I never let temporary discomfort make a permanent decision.",
  "I no longer trade the finish line for an easy exit.",
  "I never let my past quitting predict my future.",
  "I no longer let a stumble become a fall I stay down for.",
  "I never let the fear of slow ruin the value of steady.",
  "I no longer quit on the promise I made to myself.",

  // ── I NEVER / I NO LONGER — doubt & negative self-talk ──
  "I no longer speak to myself in ways I'd never speak to a friend.",
  "I never let doubt sit in the driver's seat.",
  "I no longer call myself lazy when I'm just learning.",
  "I never let my inner critic write my story.",
  "I no longer believe every negative thought I have.",
  "I never let 'I can't' go unchallenged.",
  "I no longer measure my worth by the scale.",
  "I never let shame do the coaching in my head.",
  "I no longer talk down to the body that carries me.",
  "I never let one bad photo decide how I feel.",
  "I no longer let the mirror rob my momentum.",
  "I never let old failures define new attempts.",
  "I no longer let 'I'm not the type' hold me back.",
  "I never let self-doubt cancel self-care.",
  "I no longer let my mind bully my progress.",
  "I never call my effort worthless just because it's slow.",
  "I no longer let comparison poison my confidence.",
  "I never let a hard day become proof that I'm failing.",
  "I no longer believe I've already blown it.",
  "I never let 'I always give up' be my prophecy.",
  "I no longer let a number on the scale define my day.",
  "I never let negative self-talk go unanswered.",
  "I no longer accept 'that's just how I am' as the end.",
  "I never let doubt be louder than my discipline.",
  "I no longer let fear pretend to be wisdom.",
  "I never talk myself out of believing in me.",
  "I no longer let a setback whisper that I'm not enough.",
  "I never let my worst thoughts have the last word.",
  "I no longer let 'I'll never change' run in the background.",
  "I never punish my body with my words.",
  "I no longer let the inner critic set the pace.",
  "I never let a bad day become a bad opinion of myself.",
  "I no longer believe the lie that it's too late for me.",
  "I never let self-criticism replace self-respect.",
  "I no longer let doubt undo what discipline built.",
  "I never let my mind talk me out of my worth.",
  "I no longer let old labels stick to a new me.",
  "I never let a missed goal mean I'm a failure.",
  "I no longer let my head sabotage my heart's goals.",
  "I never let harsh self-talk be my daily soundtrack.",
  "I no longer let insecurity make my choices.",
  "I never let 'not good enough' be my resting thought.",
  "I no longer let my mistakes define my identity.",
  "I never let discouragement out-argue my discipline.",
  "I no longer let fear of failing keep me from starting.",

  // ── I NEVER / I NO LONGER — comparison ──
  "I no longer measure my journey against anyone else's.",
  "I never let someone else's highlight reel dim my progress.",
  "I no longer compete with people I was never racing.",
  "I never let comparison steal my joy.",
  "I no longer shrink because someone else is further along.",
  "I never trade my pace for someone else's timeline.",
  "I no longer let another body make me forget mine.",
  "I never let social media set my standard.",
  "I no longer chase a version of health that isn't mine.",
  "I never let envy decide my worth.",
  "I no longer judge my chapter one by someone's chapter twenty.",
  "I never let comparison rewrite my goals.",
  "I no longer measure my success by other people's finish lines.",
  "I never let another woman's win feel like my loss.",
  "I no longer let comparison make me quit.",
  "I never let the internet tell me what my body should be.",
  "I no longer race a clock that isn't mine.",
  "I never let someone else's progress erase my own.",
  "I no longer scroll myself into feeling behind.",
  "I never let comparison outshine my consistency.",

  // ── I NEVER / I NO LONGER — procrastination & 'tomorrow' ──
  "I no longer save my best effort for tomorrow.",
  "I never let 'later' become never.",
  "I no longer put off the thing my body needs today.",
  "I never wait for next week to respect myself.",
  "I no longer let 'someday' hold my goals hostage.",
  "I never postpone the promise I made to me.",
  "I no longer let 'I'll start after the weekend' repeat forever.",
  "I never delay the choice my future self is counting on.",
  "I no longer treat today as a rough draft.",
  "I never let procrastination pick my priorities.",
  "I no longer wait for motivation that may not come.",
  "I never trade a small action now for a big regret later.",
  "I no longer let 'in a minute' become an hour gone.",
  "I never leave my health for a version of me who has more time.",
  "I no longer let the perfect plan delay a decent start.",
  "I never wait until January to change my life.",
  "I no longer let 'not right now' quietly mean 'not ever'.",
  "I never push my goals to a day that never arrives.",
  "I no longer let one more delay steal my momentum.",
  "I never treat my body's needs as things that can wait.",
  "I no longer let 'when things calm down' run my health.",
  "I never leave for tomorrow the workout I can do today.",
  "I no longer let planning replace doing.",
  "I never wait to be ready — I get ready by starting.",
  "I no longer let 'I'll begin when' become my excuse.",
  "I never bury today's action under tomorrow's intentions.",
  "I no longer let comfort delay my change.",
  "I never let hesitation cost me a day.",
  "I no longer let a full to-do list crowd out my well-being.",
  "I never let 'after this' become the reason nothing starts.",
  "I no longer wait for a sign to take care of myself.",
  "I never postpone becoming who I'm meant to be.",
  "I no longer let 'not today' win five days in a row.",
  "I never let the fear of starting keep me stuck.",
  "I no longer trade action for another day of thinking about it.",
  "I never leave my discipline for a more convenient moment.",
  "I no longer let procrastination masquerade as preparation.",
  "I never wait for perfect to do something good.",
  "I no longer let 'I'll get to it' outrank 'I'm doing it now'.",
  "I never let the day end with the promise still undone.",
  "I no longer treat my goals as background tasks.",
  "I never let hesitation be my habit.",
  "I no longer wait for permission to prioritize me.",
  "I never let 'eventually' become my whole plan.",
  "I no longer delay the discipline that sets me free.",

  // ── I NEVER / I NO LONGER — overeating & portions ──
  "I no longer eat until I'm uncomfortable.",
  "I never clean my plate just because it's there.",
  "I no longer let portion sizes decide for me.",
  "I never eat past the point of feeling good.",
  "I no longer confuse a second helping with a real need.",
  "I never let a big plate override my body's signals.",
  "I no longer rush through my meals.",
  "I never eat so fast I miss when I'm full.",
  "I no longer let free food talk me out of my goals.",
  "I never treat every gathering as a reason to overdo it.",
  "I no longer let portion distortion run my plate.",
  "I never eat to get my money's worth.",
  "I no longer finish it just so it isn't wasted.",
  "I never let one indulgent meal become an all-day pass.",
  "I no longer graze without noticing.",
  "I never let seconds be automatic.",
  "I no longer eat past satisfied to reach stuffed.",
  "I never let big portions be my default.",
  "I no longer ignore the moment my body says enough.",
  "I never let the size of the plate set the size of the meal.",

  // ── I NEVER / I NO LONGER — rest, sleep, water & recovery neglect ──
  "I no longer sacrifice my sleep for one more episode.",
  "I never treat rest as something I have to earn.",
  "I no longer run on empty and call it dedication.",
  "I never skip water and wonder why I feel off.",
  "I no longer ignore what my body is trying to tell me.",
  "I never trade recovery for the illusion of doing more.",
  "I no longer let a screen steal the sleep I need.",
  "I never push through pain that's asking me to rest.",
  "I no longer let exhaustion pretend to be discipline.",
  "I never neglect the rest that makes the work count.",
  "I no longer stay up late at my body's expense.",
  "I never treat hydration as an afterthought.",
  "I no longer skip rest days and call it commitment.",
  "I never confuse burnout with hard work.",
  "I no longer let stress rob my sleep without a fight.",
  "I never ignore the recovery my muscles are begging for.",
  "I no longer let 'I'll sleep when I'm dead' run my life.",
  "I never skip the water my body runs on.",
  "I no longer treat rest as laziness.",
  "I never punish my body by refusing it recovery.",
  "I no longer let a full calendar cancel my sleep.",
  "I never mistake being tired for being weak.",
  "I no longer grind through the rest I clearly need.",
  "I never let poor sleep sabotage my best effort.",
  "I no longer treat my body like it has no limits.",
  "I never neglect the quiet work that recovery does.",
  "I no longer let hustle culture rob my rest.",
  "I never forget that rest is part of the plan.",
  "I no longer wear exhaustion like a badge.",
  "I never let dehydration masquerade as hunger.",
  "I no longer skip the recovery that protects my progress.",
  "I never let one late night undo my whole week.",
  "I no longer treat sleep as the first thing to cut.",
  "I never ignore my body's need to slow down.",
  "I no longer let stress steal the rest I've earned.",
  "I never sacrifice recovery to prove I'm tough.",
  "I no longer run myself into the ground for approval.",
  "I never treat my need for rest as a flaw.",
  "I no longer skip the water that keeps me sharp.",
  "I never let a packed schedule starve my recovery.",

  // ── I NEVER / I NO LONGER — broken promises & accountability ──
  "I no longer break the promises I make to myself.",
  "I never let myself be the one person I let down.",
  "I no longer say I'll do it and quietly don't.",
  "I never treat my own word as the easiest to break.",
  "I no longer keep everyone's commitments but mine.",
  "I never let my goals become empty declarations.",
  "I no longer let 'I'll be good tomorrow' off the hook.",
  "I never lie to my tracker to feel better.",
  "I no longer hide from the numbers that tell the truth.",
  "I never skip my check-in to avoid facing it.",
  "I no longer let no one holding me accountable mean I don't have to be.",
  "I never let being my own boss mean having no standards.",
  "I no longer promise change and deliver the same.",
  "I never let my intentions outpace my actions.",
  "I no longer keep score in a way that lets me cheat.",
  "I never let 'no one will know' change my choices.",
  "I no longer treat accountability as something for other people.",
  "I never dodge the honest look in the mirror.",
  "I no longer let my excuses off without a hearing.",
  "I never let a missed goal go unexamined.",
  "I no longer avoid the scale because I'm scared of it.",
  "I never make a plan I have no intention of keeping.",
  "I no longer let secrecy be the loophole in my discipline.",
  "I never treat my promises to me as negotiable.",
  "I no longer let a quiet quit slide by unnoticed.",
  "I never break a streak and pretend it didn't matter.",
  "I no longer let 'I forgot' cover for 'I avoided it'.",
  "I never leave my own goals unmanaged.",
  "I no longer let myself off easy when it counts.",
  "I never trade my integrity for a comfortable excuse.",
  "I no longer keep the promise only when someone's watching.",
  "I never let accountability be optional for me.",
  "I no longer soften the truth to protect my comfort.",
  "I never let my log tell a story my day didn't.",
  "I no longer skip the follow-through that makes goals real.",
  "I never let a missed workout go without an honest reckoning.",
  "I no longer let 'close enough' pass for kept my word.",
  "I never abandon the standard I set for myself.",
  "I no longer let my future self clean up my broken promises.",
  "I never treat my commitments to me as less than sacred.",
  "I no longer let 'just this week' become a permanent pass.",
  "I never let being unseen lower my standard.",
  "I no longer break trust with myself and call it a break.",
  "I never let my goals live only in my head.",
  "I no longer let accountability end where the audience does.",

  // ── I NEVER / I NO LONGER — old identity & who I used to be ──
  "I no longer live as the person my old habits made.",
  "I never let my past self run my present choices.",
  "I no longer answer to the excuses I used to make.",
  "I never let 'the old me' finish my sentences.",
  "I no longer carry habits that were never really mine.",
  "I never let who I was outvote who I'm becoming.",
  "I no longer recognize giving up as an option.",
  "I never let my former limits define my future.",
  "I no longer let my old story predict my new one.",
  "I never dress in an identity I've already outgrown.",
  "I no longer let the person I was talk me out of the person I am.",
  "I never let a past failure own my present.",
  "I no longer make choices to match an old self-image.",
  "I never let 'I've always been this way' be the ending.",
  "I no longer honor habits that hold me back.",
  "I never let yesterday's version of me lower today's bar.",
  "I no longer let my old comfort zone feel like home.",
  "I never let the past write my future in advance.",
  "I no longer let my history be my forecast.",
  "I never let who I used to be shame who I'm working to become.",
  "I no longer keep an identity that keeps me small.",
  "I never let 'that's just me' excuse what I can change.",
  "I no longer let old patterns run on autopilot.",
  "I never let the me from a year ago set today's limits.",
  "I no longer let outdated beliefs about myself stick.",
  "I never let my old defaults override my new decisions.",
  "I no longer live down to my former expectations.",
  "I never let my past define what my body can do.",
  "I no longer let the habits I'm leaving choose for me.",
  "I never let 'I could never' be a permanent address.",
  "I no longer let my old cravings speak for the new me.",
  "I never let a former setback set my ceiling.",
  "I no longer wear the labels I've decided to drop.",
  "I never let the person I'm leaving behind lead the way.",
  "I no longer let old shame steer new choices.",
  "I never let my worst season define my whole story.",
  "I no longer let 'this is just how I eat' be unchangeable.",
  "I never let the past be the boss of my present.",
  "I no longer identify with the habits I'm breaking.",
  "I never let my old ceiling become my new floor's limit.",
  "I no longer let who I was decide who I'll be.",
  "I never let an old excuse wear new clothes.",
  "I no longer let my former giving-up be my go-to move.",
  "I never let the past me set the pace for the present me.",
  "I no longer let old habits masquerade as my personality.",

  // ── I NEVER / I NO LONGER — consistency & momentum ──
  "I no longer let a broken streak break my resolve.",
  "I never let one missed day erase my momentum.",
  "I no longer need to be perfect to be consistent.",
  "I never let a gap in the routine become a canyon.",
  "I no longer treat consistency as all-or-nothing.",
  "I never let a slow week convince me to stop showing up.",
  "I no longer wait for a fresh start to be consistent.",
  "I never let a stumble reset my whole streak in my mind.",
  "I no longer let momentum slip without noticing.",
  "I never let 'I already broke it' cancel the rest of the week.",
  "I no longer let one skipped rep become a skipped habit.",
  "I never let the small daily work feel too small to matter.",
  "I no longer trade steady progress for a burst that fades.",
  "I never let boredom break my routine.",
  "I no longer let a hard Monday ruin the whole week.",
  "I never let consistency depend on how I feel.",
  "I no longer let a disrupted schedule end the habit.",
  "I never let 'I'll get back to it' replace getting back to it.",
  "I no longer let one lapse become my new pattern.",
  "I never underestimate the power of one more day of showing up.",
  "I no longer let missing once mean missing twice.",
  "I never let a busy season delete my good habits.",
  "I no longer let the fear of breaking a streak keep me from restarting it.",
  "I never let consistency wait for convenience.",
  "I no longer treat small steps as too little to count.",
  "I never let a detour become a dead end.",
  "I no longer let a rough patch break the rhythm for good.",
  "I never let 'I'm not seeing results' stop my reps.",
  "I no longer let disruption become an excuse to disappear.",
  "I never let the pause become the period.",
  "I no longer let my habits hinge on a perfect week.",
  "I never let a single off day rewrite my identity.",
  "I no longer let momentum die quietly on the hard days.",
  "I never let a break become a breakup with my goals.",
  "I no longer let the missed day be louder than the many I kept.",
  "I never let one bad week outweigh a good month.",
  "I no longer let consistency be conditional.",
  "I never let a slow start slow my whole journey.",
  "I no longer let 'I fell off' keep me on the ground.",
  "I never let showing up become negotiable.",
  "I no longer let a broken habit stay broken.",
  "I never let one skipped day cost me the streak in my head.",
  "I no longer let inconsistency become my identity.",
  "I never let a missed rep undo my resolve.",
  "I no longer let the gap decide the story.",

  // ── I AM / IT'S LIKE ME NOW — disciplined & consistent identity ──
  "I am someone who shows up whether I feel like it or not.",
  "It's like me now to do the work even when it's hard.",
  "I am the kind of person who keeps promises to myself.",
  "It's like me now to move my body every single day.",
  "I am disciplined, and my choices prove it.",
  "It's like me now to choose the goal over the mood.",
  "I am consistent, one honest day at a time.",
  "It's like me now to finish what I start.",
  "I am someone who does hard things on purpose.",
  "It's like me now to keep going when it's slow.",
  "I am the person my future self is counting on.",
  "It's like me now to train even on the tired days.",
  "I am steady, and steady is what builds me.",
  "It's like me now to follow through without being reminded.",
  "I am someone who turns intentions into action.",
  "It's like me now to protect my routine like it matters.",
  "I am reliable to myself first.",
  "It's like me now to show up before I feel ready.",
  "I am the type who does it now, not later.",
  "It's like me now to make the promise and keep it.",
  "I am disciplined enough to be free.",
  "It's like me now to choose long-term over easy.",
  "I am someone who honors the plan I made.",
  "It's like me now to keep my word to me.",
  "I am consistent in the small things that add up.",
  "It's like me now to earn my own respect daily.",
  "I am the woman who doesn't quit on herself.",
  "It's like me now to do it whether or not anyone sees.",
  "I am becoming unshakable, rep by rep.",
  "It's like me now to trust my routine over my mood.",
  "I am someone who takes the next right step.",
  "It's like me now to keep the streak alive.",
  "I am proof that discipline beats motivation.",
  "It's like me now to work quietly and win loudly.",
  "I am the kind of person who does what I say.",
  "It's like me now to choose action over excuses.",
  "I am dependable when it comes to my own goals.",
  "It's like me now to keep showing up regardless.",
  "I am building a life my discipline is proud of.",
  "It's like me now to make consistency my superpower.",
  "I am someone who plans the work and works the plan.",
  "It's like me now to start before the motivation shows up.",
  "I am relentless in the gentlest, steadiest way.",
  "It's like me now to be my own kind of unstoppable.",
  "I am the person who does the boring reps that build greatness.",
  "It's like me now to take care of business, then rest.",
  "I am someone who keeps going after the excitement fades.",
  "It's like me now to choose the harder right over the easier wrong.",
  "I am consistent because I decided to be.",
  "It's like me now to make showing up non-negotiable.",
  "I am the version of me who keeps her word.",
  "It's like me now to let my actions do the talking.",
  "I am building discipline into a habit I can trust.",
  "It's like me now to keep promises when no one's watching.",
  "I am someone who does today what my goals require.",
  "It's like me now to be steady when life is not.",
  "I am the kind of consistent that changes everything.",
  "It's like me now to show up for me first.",
  "I am someone who lets discipline set me free.",
  "It's like me now to make the disciplined choice feel normal.",

  // ── I AM / IT'S LIKE ME NOW — strong & capable ──
  "I am stronger than the excuse that shows up today.",
  "It's like me now to do one more rep than I think I can.",
  "I am capable of more than my comfort zone admits.",
  "It's like me now to lift heavier than my doubts.",
  "I am building strength that shows up off the mat too.",
  "It's like me now to meet the hard set head-on.",
  "I am powerful, and my body is proof.",
  "It's like me now to push through the last hard minute.",
  "I am strong in body and steady in mind.",
  "It's like me now to treat challenges as training.",
  "I am tougher than the day trying to break me.",
  "It's like me now to finish strong when it burns.",
  "I am the strongest I've ever been, and still climbing.",
  "It's like me now to embrace the weight, not fear it.",
  "I am capable of carrying what I once couldn't.",
  "It's like me now to turn 'I can't' into 'watch me'.",
  "I am building a body that keeps its promises.",
  "It's like me now to be surprised by my own strength.",
  "I am proof that hard work reshapes what's possible.",
  "It's like me now to rise to the heavy days.",
  "I am strong enough to keep going when it's hard.",
  "It's like me now to make effort feel like home.",
  "I am becoming more capable with every session.",
  "It's like me now to trust what my body can do.",
  "I am powerful because I keep showing up.",
  "It's like me now to lean into the challenge.",
  "I am resilient, and resilience is a muscle I train.",
  "It's like me now to do the thing that scares me a little.",
  "I am strong in ways the mirror is just starting to show.",
  "It's like me now to let the hard reps build me.",
  "I am capable, prepared, and ready for today.",
  "It's like me now to meet resistance with resolve.",
  "I am the kind of strong that starts on the inside.",
  "It's like me now to earn my strength one set at a time.",
  "I am more powerful than I give myself credit for.",
  "It's like me now to push past the point I used to stop.",
  "I am built to handle hard things.",
  "It's like me now to grow through what I go through.",
  "I am strong, and I am still becoming stronger.",
  "It's like me now to answer the challenge with action.",
  "I am capable of change, and I prove it daily.",
  "It's like me now to make my body a source of pride.",
  "I am the definition of getting stronger every week.",
  "It's like me now to treat every rep as an investment.",
  "I am a force, and I am just getting started.",

  // ── I AM / IT'S LIKE ME NOW — nourishing & eating well ──
  "I am someone who fuels her body like she loves it.",
  "It's like me now to eat in a way that respects my goals.",
  "I am nourished, not deprived.",
  "It's like me now to choose foods that fuel my day.",
  "I am in control of what's on my plate.",
  "It's like me now to eat with intention, not on autopilot.",
  "I am someone who hits my protein because I value muscle.",
  "It's like me now to enjoy food without letting it run me.",
  "I am the kind of person who eats to feel strong.",
  "It's like me now to fill my plate with what serves me.",
  "I am at peace with food and in charge of my choices.",
  "It's like me now to stop when I'm satisfied.",
  "I am someone who plans my meals like they matter.",
  "It's like me now to make the nourishing choice feel easy.",
  "I am eating for the body I'm building.",
  "It's like me now to treat food as fuel, not a fix.",
  "I am mindful with every bite I take.",
  "It's like me now to prep so my goals aren't left to chance.",
  "I am someone who eats enough to thrive.",
  "It's like me now to choose whole food that loves me back.",
  "I am fueling strength, energy, and clarity.",
  "It's like me now to eat like I respect my future.",
  "I am kind to my body through what I feed it.",
  "It's like me now to keep my cravings in their place.",
  "I am someone who eats to win, not to hide.",
  "It's like me now to make protein and produce my defaults.",
  "I am the person who drinks her water first.",
  "It's like me now to nourish before I indulge.",
  "I am satisfied by food that actually serves me.",
  "It's like me now to eat calmly and slowly.",
  "I am someone who cooks for the woman I'm becoming.",
  "It's like me now to fuel my workouts on purpose.",
  "I am building my body one good meal at a time.",
  "It's like me now to choose the plate that fits my plan.",
  "I am done letting food have power over my peace.",
  "It's like me now to eat for energy, not for escape.",
  "I am someone who honors hunger and honors fullness.",
  "It's like me now to make healthy eating my normal.",
  "I am nourished, strong, and in charge.",
  "It's like me now to feed the goal, not the mood.",
  "I am someone who eats with my future in mind.",
  "It's like me now to let good food be a form of self-respect.",
  "I am proof that eating well can taste like freedom.",
  "It's like me now to prep, portion, and progress.",
  "I am fueling a comeback with every meal.",
  "It's like me now to treat my plate as part of my training.",
  "I am someone food no longer controls.",
  "It's like me now to keep it simple, strong, and nourishing.",
  "I am eating like the athlete I'm becoming.",
  "It's like me now to make hydration a habit I don't skip.",

  // ── I AM / IT'S LIKE ME NOW — confidence & body image ──
  "I am proud of the body that's carrying me through this.",
  "It's like me now to speak kindly to myself.",
  "I am confident in the woman I'm becoming.",
  "It's like me now to celebrate progress, not chase perfect.",
  "I am worthy of the effort I put in.",
  "It's like me now to look in the mirror with respect.",
  "I am more than a number on a scale.",
  "It's like me now to notice my wins, not just my gaps.",
  "I am comfortable becoming the fullest version of me.",
  "It's like me now to thank my body for what it does.",
  "I am growing into confidence I didn't used to have.",
  "It's like me now to stand a little taller each week.",
  "I am beautiful in progress and in process.",
  "It's like me now to trust the reflection is changing.",
  "I am building confidence one kept promise at a time.",
  "It's like me now to see effort as something to be proud of.",
  "I am someone who owns her progress boldly.",
  "It's like me now to give myself credit where it's due.",
  "I am learning to love the body I'm building.",
  "It's like me now to let confidence come from consistency.",
  "I am enough, and I'm still becoming more.",
  "It's like me now to feel strong in my own skin.",
  "I am proud of every step, even the small ones.",
  "It's like me now to talk to myself like someone I love.",
  "I am confident because I keep showing up for me.",
  "It's like me now to see my body as a partner, not a project.",
  "I am worthy of feeling good in my own body.",
  "It's like me now to carry myself like I've earned it.",
  "I am done shrinking to fit anyone's expectations.",
  "It's like me now to let my confidence be quiet and real.",
  "I am becoming someone I'm proud to be.",
  "It's like me now to honor how far I've come.",
  "I am growing more sure of myself every day.",
  "It's like me now to wear my progress with pride.",
  "I am a work in progress and a masterpiece at once.",
  "It's like me now to believe I'm capable of change.",
  "I am confident, even on the days it's a choice.",
  "It's like me now to see my reflection as a friend.",
  "I am proud of the discipline behind my results.",
  "It's like me now to feel at home in my own strength.",
  "I am confident in my direction, even mid-journey.",
  "It's like me now to celebrate the body that shows up.",
  "I am someone who believes she deserves to feel good.",
  "It's like me now to let self-respect lead the way.",
  "I am becoming the confident woman I always pictured.",

  // ── I AM / IT'S LIKE ME NOW — accountable & follow-through ──
  "I am accountable to myself, first and always.",
  "It's like me now to keep score honestly.",
  "I am someone who follows through without an audience.",
  "It's like me now to do my check-in even when it's hard.",
  "I am the one who holds myself to my word.",
  "It's like me now to face the numbers with courage.",
  "I am honest with myself about my choices.",
  "It's like me now to own my slip-ups and adjust.",
  "I am responsible for my results, and I like it that way.",
  "It's like me now to track the truth, not the story.",
  "I am someone who shows up to her own commitments.",
  "It's like me now to answer to my goals daily.",
  "I am accountable because I respect myself too much not to be.",
  "It's like me now to log it honestly, every time.",
  "I am the kind of person who reviews and recommits.",
  "It's like me now to keep my promises to me sacred.",
  "I am reliable when it comes to my own health.",
  "It's like me now to hold the standard I set.",
  "I am someone who does the follow-through others skip.",
  "It's like me now to check in and course-correct.",
  "I am the author of my accountability.",
  "It's like me now to face the mirror and the metrics honestly.",
  "I am consistent about being honest with myself.",
  "It's like me now to make no-excuses my default.",
  "I am someone who keeps the receipts on my effort.",
  "It's like me now to be the accountability I used to look for.",
  "I am responsible, honest, and following through.",
  "It's like me now to close the loop on what I start.",
  "I am someone who owns the outcome and the effort.",
  "It's like me now to do the check-in that keeps me honest.",
  "I am accountable whether or not anyone is looking.",
  "It's like me now to turn intentions into logged action.",
  "I am the person who does what she said she'd do.",
  "It's like me now to measure honestly and move forward.",
  "I am committed to keeping my own standards high.",
  "It's like me now to answer for my week with pride.",
  "I am someone whose actions match her words.",
  "It's like me now to stay honest when it's inconvenient.",
  "I am accountable, and that's my quiet power.",
  "It's like me now to make follow-through a reflex.",
  "I am someone who checks in instead of checking out.",
  "It's like me now to own it all and keep going.",
  "I am the standard I've been waiting for.",
  "It's like me now to hold the line I drew for myself.",
  "I am accountable, and it's setting me free.",

  // ── I AM / IT'S LIKE ME NOW — a mover, active by nature ──
  "I am someone who moves her body because she can.",
  "It's like me now to take the stairs on purpose.",
  "I am active, and movement is part of who I am.",
  "It's like me now to get my steps without thinking twice.",
  "I am the kind of person who chooses to move.",
  "It's like me now to stretch, walk, and stay loose.",
  "I am someone who never sits still for too long.",
  "It's like me now to find joy in moving.",
  "I am energized by the movement I once avoided.",
  "It's like me now to treat a walk as a gift, not a chore.",
  "I am someone who trains because she loves what it builds.",
  "It's like me now to move even on my rest days, gently.",
  "I am active in body and it lifts my whole mood.",
  "It's like me now to choose motion over stillness.",
  "I am the person who looks forward to her workout.",
  "It's like me now to move like it's a privilege.",
  "I am someone whose default is to get moving.",
  "It's like me now to shake off a bad mood with movement.",
  "I am strong because I keep my body in motion.",
  "It's like me now to sweat on purpose and enjoy it.",
  "I am a mover, a lifter, and a finisher.",
  "It's like me now to make exercise a part of my day.",
  "I am someone whose body loves to be used.",
  "It's like me now to walk it out when I need to think.",
  "I am active because it's who I've decided to be.",
  "It's like me now to move first and feel better after.",
  "I am energized by movement, not drained by it.",
  "It's like me now to find any reason to get active.",
  "I am the kind of person who moves through her feelings.",
  "It's like me now to treat my body like it was made to move.",
  "I am someone who makes movement non-negotiable.",
  "It's like me now to be the one who suggests the walk.",
  "I am at my best when I keep my body moving.",
  "It's like me now to let movement be my medicine.",
  "I am a naturally active version of myself now.",
  "It's like me now to move my body as an act of love.",
  "I am someone who never dreads the gym anymore.",
  "It's like me now to see workouts as 'get to', not 'have to'.",
  "I am building a life full of movement I enjoy.",
  "It's like me now to keep moving toward who I'm becoming.",

  // ── I AM / IT'S LIKE ME NOW — recovery, rest & self-care ──
  "I am someone who rests without guilt.",
  "It's like me now to protect my sleep like it's training.",
  "I am wise enough to let my body recover.",
  "It's like me now to drink my water before I'm thirsty.",
  "I am someone who honors rest as part of the work.",
  "It's like me now to slow down when my body asks.",
  "I am at peace giving my muscles time to rebuild.",
  "It's like me now to take my rest day seriously.",
  "I am someone who treats recovery as non-negotiable.",
  "It's like me now to prioritize sleep like it matters.",
  "I am gentle with my body when it needs gentleness.",
  "It's like me now to listen when my body says rest.",
  "I am someone who refills before she runs empty.",
  "It's like me now to make recovery part of my plan.",
  "I am kind to my body on the days it needs slowing.",
  "It's like me now to let rest make my next effort count.",
  "I am someone who values recovery as much as effort.",
  "It's like me now to stretch, breathe, and reset.",
  "I am balanced between pushing hard and resting well.",
  "It's like me now to guard my sleep from the little thieves.",
  "I am someone who recovers on purpose.",
  "It's like me now to treat rest as productive.",
  "I am at my strongest when I'm also well-rested.",
  "It's like me now to give my body what it needs to bounce back.",
  "I am someone who knows when to push and when to pause.",
  "It's like me now to end my day with rest, not regret.",
  "I am restored by the rest I no longer skip.",
  "It's like me now to make self-care a habit, not a reward.",
  "I am someone who fuels recovery like she fuels effort.",
  "It's like me now to treat my body like it's worth caring for.",

  // ── I AM / IT'S LIKE ME NOW — growth, becoming & heart ──
  "I am becoming the healthiest version of myself.",
  "It's like me now to grow a little every single day.",
  "I am a work in progress, and that's exactly right.",
  "It's like me now to keep becoming who I'm meant to be.",
  "I am someone who improves instead of standing still.",
  "It's like me now to see every day as a step forward.",
  "I am grateful for a body that lets me try again.",
  "It's like me now to treat my health as a form of gratitude.",
  "I am growing stronger in body, mind, and spirit.",
  "It's like me now to steward the body I've been given.",
  "I am becoming someone my future self will thank.",
  "It's like me now to turn small wins into a new life.",
  "I am the kind of person who keeps leveling up.",
  "It's like me now to believe change is always possible.",
  "I am proof that a fresh start can hold.",
  "It's like me now to grow through the hard seasons.",
  "I am someone who honors this body as a gift.",
  "It's like me now to build a healthier life on purpose.",
  "I am becoming, and becoming is beautiful.",
  "It's like me now to root my discipline in self-respect.",
  "I am grateful for the strength this journey is giving me.",
  "It's like me now to grow with grace and grit.",
  "I am someone whose best days are still ahead.",
  "It's like me now to treat progress as a promise I keep.",
  "I am learning, growing, and getting better every week.",
  "It's like me now to see setbacks as setups for growth.",
  "I am becoming unrecognizable to my old doubts.",
  "It's like me now to grow into the goals I set.",
  "I am someone who takes care of the one body I have.",
  "It's like me now to lead my life with intention.",
  "I am worthy of a strong, healthy, thriving life.",
  "It's like me now to keep planting what I want to harvest.",
  "I am a testimony in progress.",
  "It's like me now to grow steadily toward my goals.",
  "I am becoming the woman I've prayed to be.",
  "It's like me now to honor my body with how I live.",
  "I am someone who keeps rising, no matter what.",
  "It's like me now to treat every day as a chance to grow.",
  "I am the author of a comeback story.",
  "It's like me now to build a life I'm proud of, one choice at a time.",

  // ── I AM / IT'S LIKE ME NOW — habits & systems ──
  "I am someone whose good habits run on autopilot.",
  "It's like me now to prep so success is the easy option.",
  "I am building systems that make discipline simple.",
  "It's like me now to set my day up to win.",
  "I am someone who makes the healthy choice the default.",
  "It's like me now to plan tomorrow before it arrives.",
  "I am the kind of person who removes the friction.",
  "It's like me now to keep my routines simple and strong.",
  "I am someone who lets my habits carry me on hard days.",
  "It's like me now to stack small wins into big change.",
  "I am building a life where good choices feel normal.",
  "It's like me now to make my environment work for me.",
  "I am someone whose habits reflect her goals.",
  "It's like me now to let routine do the heavy lifting.",
  "I am the person who preps meals and packs the bag.",
  "It's like me now to make consistency automatic.",
  "I am someone who trusts her systems over her willpower.",
  "It's like me now to design my days around my goals.",
  "I am building habits that will outlast my motivation.",
  "It's like me now to make the next right choice obvious.",
  "I am someone who keeps the streak by keeping it simple.",
  "It's like me now to let structure set me free.",
  "I am the kind of person whose habits do the work.",
  "It's like me now to build routines I can keep forever.",
  "I am someone who protects her habits like they matter.",
  "It's like me now to make healthy the path of least resistance.",
  "I am building a foundation one habit at a time.",
  "It's like me now to let my systems catch me on the off days.",
  "I am someone who plans the win before the day starts.",
  "It's like me now to turn discipline into routine.",
  "I am the person whose habits point toward her dreams.",
  "It's like me now to keep my promises through my systems.",
  "I am building an identity out of tiny daily choices.",
  "It's like me now to make good habits my normal.",
  "I am someone whose routines run toward her goals.",
  "It's like me now to trust the process I've built.",
  "I am proof that habits shape a whole life.",
  "It's like me now to let my systems carry my goals.",
  "I am the kind of person who makes success repeatable.",
  "It's like me now to build the habits that build me.",

  // ── I NEVER / I NO LONGER — mornings & starting the day ──
  "I no longer let a slow morning steal my whole day.",
  "I never hit snooze on my goals.",
  "I no longer start my day feeding my phone before my body.",
  "I never let a chaotic morning cancel my discipline.",
  "I no longer wake up dreading the work I chose.",
  "I never let the first hard hour decide the day.",
  "I no longer let a late alarm be a whole excuse.",
  "I never skip breakfast planning and coast on cravings.",
  "I no longer let the morning rush win.",
  "I never let 'I woke up late' become 'I'll skip it'.",

  // ── I NEVER / I NO LONGER — weekends, holidays & social pressure ──
  "I no longer let the weekend undo the week.",
  "I never treat Saturday as a day off from myself.",
  "I no longer let holidays erase my whole plan.",
  "I never let a party be a reason to abandon my goals.",
  "I no longer eat off-plan just to make others comfortable.",
  "I never let peer pressure override my priorities.",
  "I no longer let 'everyone else is' decide my plate.",
  "I never let a celebration become a full surrender.",
  "I no longer let vacation cancel every good habit.",
  "I never let one event become a lost week.",
  "I no longer let others' choices talk me out of mine.",
  "I never let 'live a little' become 'lose it all'.",
  "I no longer let a night out ruin a whole month.",
  "I never let social plans be an excuse to give up.",
  "I no longer feel bad for keeping my own standards in a crowd.",
  "I never let the buffet undo my discipline.",
  "I no longer let 'it's a special occasion' repeat every week.",
  "I never let someone else's plate dictate mine.",
  "I no longer let a full weekend become a wasted one.",
  "I never let people-pleasing outrank self-respect.",

  // ── I NEVER / I NO LONGER — alcohol, screens & numbing ──
  "I no longer drink away the progress I worked for.",
  "I never let a nightcap steal my morning.",
  "I no longer numb my stress with things that set me back.",
  "I never trade my goals for a temporary escape.",
  "I no longer let the couch and the screen eat my evening.",
  "I never let endless scrolling replace real rest.",
  "I no longer let a screen keep me from my workout.",
  "I never drown my discipline in distraction.",
  "I no longer let one drink become a reason to quit for the night.",
  "I never let comfort habits quietly cost me my goals.",

  // ── I NEVER / I NO LONGER — the scale & measuring worth ──
  "I no longer let the scale ruin a good day.",
  "I never let one weigh-in define my whole effort.",
  "I no longer chase the scale and ignore the mirror.",
  "I never let a number override how far I've come.",
  "I no longer let water weight steal my confidence.",
  "I never let the scale be the only measure of my win.",
  "I no longer weigh my worth in pounds.",
  "I never let a stuck number make me quit.",
  "I no longer let the scale coach me into giving up.",
  "I never let a bad weigh-in erase good habits.",

  // ── I NEVER / I NO LONGER — patience & the process ──
  "I no longer expect overnight results from long-game work.",
  "I never let impatience talk me out of the process.",
  "I no longer demand proof before I trust the plan.",
  "I never let 'it's not fast enough' end my effort.",
  "I no longer let a slow week make me forget the goal.",
  "I never let the long road convince me to turn back.",
  "I no longer rush the results and skip the reps.",
  "I never let a plateau feel like the end of the road.",
  "I no longer trade patience for a quick fix that fails.",
  "I never let the wait steal my willingness to work.",
  "I no longer expect the finish line before I've run the miles.",
  "I never let slow-and-steady feel like standing still.",
  "I no longer let a quiet week convince me nothing's happening.",
  "I never abandon a plan that just needs more time.",
  "I no longer let impatience rob me of the payoff.",

  // ── I NEVER / I NO LONGER — the gym & the work itself ──
  "I no longer let the gym intimidate me out of showing up.",
  "I never let not knowing everything stop me from starting.",
  "I no longer skip the workout because it looks hard.",
  "I never let a crowded gym be my excuse.",
  "I no longer let fear of judgment keep me on the sidelines.",
  "I never let 'I don't belong here' win.",
  "I no longer avoid the weights I'm ready to lift.",
  "I never let one tough workout scare me off the next.",
  "I no longer let soreness talk me out of tomorrow.",
  "I never let the hardest set decide I'm done.",
  "I no longer shrink in a room full of stronger people.",
  "I never let not being the best keep me from getting better.",
  "I no longer let the fear of looking silly stop my growth.",
  "I never let an off session ruin my belief in the work.",
  "I no longer wait to feel confident before I begin.",

  // ── I NEVER / I NO LONGER — food guilt & the reset trap ──
  "I no longer punish myself for one off-plan meal.",
  "I never let food guilt spiral into more bad choices.",
  "I no longer let 'I ruined it' cost me the whole day.",
  "I never treat one cookie as a reason to eat ten.",
  "I no longer let shame do the ordering.",
  "I never let guilt convince me to wait until Monday.",
  "I no longer let a single indulgence cancel my identity.",
  "I never let food guilt steal my next good choice.",
  "I no longer let one slip become the whole story.",
  "I never let regret keep me from getting right back on track.",
  "I no longer let a missed macro undo my week in my head.",
  "I never let 'I already blew it' be permission to keep going.",
  "I no longer let guilt outweigh grace with myself.",
  "I never let a treat turn into a two-day tailspin.",
  "I no longer let one meal define my whole day.",

  // ── I NEVER / I NO LONGER — energy, mood & motivation ──
  "I no longer wait for motivation to do the work.",
  "I never let a low-energy day equal a no-effort day.",
  "I no longer let a bad mood run my whole plan.",
  "I never let feelings have veto power over my goals.",
  "I no longer confuse not wanting to with not being able to.",
  "I never let 'I'm not feeling it' be the final word.",
  "I no longer let a heavy heart skip a light workout.",
  "I never let motivation be the only thing that moves me.",
  "I no longer let one flat day flatten my whole week.",
  "I never let my emotions cancel my commitments.",
  "I no longer wait to feel ready to take care of myself.",
  "I never let a low mood become a low standard.",
  "I no longer let 'meh' decide my movement.",
  "I never let my energy dictate my discipline.",
  "I no longer let a hard feeling stop a healthy choice.",

  // ── I NEVER / I NO LONGER — self-worth & finishing ──
  "I no longer believe I'm the exception who can't change.",
  "I never let 'this won't work for me' go untested.",
  "I no longer count myself out before I try.",
  "I never let past failures forbid future wins.",
  "I no longer treat my goals as too big for me.",
  "I never let 'people like me don't' write my ending.",
  "I no longer let one setback cancel my belief in myself.",
  "I never abandon the finish because the middle is hard.",
  "I no longer let doubt outlast my determination.",
  "I never let my dreams feel undeserved.",
  "I no longer talk myself out of what I'm capable of.",
  "I never let 'not for me' be the reason I quit.",
  "I no longer let fear of finishing keep me from starting.",
  "I never let the size of the goal shrink my effort.",
  "I no longer let 'it's too late' rob my comeback.",

  // ── I AM / IT'S LIKE ME NOW — a few more ──
  "I am someone who begins before I feel ready.",
  "It's like me now to bet on myself and back it up.",
  "I am proof that ordinary days build extraordinary change.",
  "It's like me now to keep the promise on the hard days too.",
  "I am the comeback I've been waiting on.",

  // ── I NEVER / I NO LONGER — final ten ──
  "I no longer let a hard day steal an easy win.",
  "I never let 'I'll be good later' replace being good now.",
  "I no longer let my goals sit at the bottom of the list.",
  "I never let a small setback become a big story.",
  "I no longer let the fear of failing keep me comfortable.",
  "I never let my past be an excuse for my present.",
  "I no longer let one weak choice choose the next.",
  "I never let 'good enough' quietly lower my standard.",
  "I no longer let discomfort make my long-term decisions.",
  "I never let a single day off become a way of life.",
]

// Pick one affirmation for the whole day. Spread across the pool so consecutive
// days aren't neighbors, and every line eventually gets its turn.
export function affirmationForToday(): string {
  const dayNumber = Math.floor(Date.now() / 86400000) // whole days since epoch (UTC)
  const idx = (dayNumber * 919) % AFFIRMATIONS.length // 919 is prime → walks the whole pool
  return AFFIRMATIONS[idx]
}
