// AUTO-GENERATED from The-Menu.html cookbook (2026-07-23). Step-by-step cooking
// directions per recipe, matched by exact name against lib/recipes.ts. Only recipes
// that actually need directions are covered here — simple grab-and-go snacks (e.g.
// "Banana + Nut Butter") don't have a directions section in the source doc.
export const RECIPE_INSTRUCTIONS: Record<string, string[]> = {
  'Chicken Nugget Hash Brown Bake': [
    'Mix all base ingredients in a 13 oz oven-safe container.',
    'Bake at 375°F for 30 min until eggs are cooked through.',
    'Add cheese on top and heat again until melted.',
    'Top with pico and enjoy.',
  ],
  'Beef & Egg Breakfast Power Bowl': [
    'Season beef with paprika, garlic, onion, pepper, salt. Brown in large skillet. Drain.',
    'Chop bacon into small pieces. Cook until crispy.',
    'Scramble eggs with all-purpose seasoning.',
    'Spread potatoes on sheet pan. Spray with oil. Bake 400°F for 20 min. Broil 500°F for 10 min.',
    'Combine all ingredients. Mix evenly.',
    'Weigh total. Divide by 10. Portion into 10 containers.',
  ],
  'Steak, Egg & Cheese Breakfast Bagels': [
    'Cook steak to 125°F internal. Rest 5 min. Slice thin.',
    'Cook bacon until crispy.',
    'Cook eggs your way.',
    'Toast Sola protein bagels.',
    'Assemble: bagel → steak → bacon → egg → cheese → top.',
    'Wrap in foil for storage.',
  ],
  'Turkey Sausage Sweet Potato Hash': [
    'Dice sweet potatoes. Toss with cooking spray. Roast at 400°F for 20 min.',
    'Season turkey with paprika, garlic, salt, pepper. Brown in large skillet. Drain.',
    'Chop bacon into small pieces. Cook until crispy.',
    'Sauté peppers & onion 3–4 min.',
    'Combine all ingredients. Mix evenly.',
    'Portion into 4 containers.',
  ],
  'BBQ Chicken Pizza': [
    'Season chicken with Italian, salt, red pepper. Cook 3–5 min per side (160°F+).',
    'Dice chicken.',
    'Spread BBQ sauce on pizza crust.',
    'Add cheese evenly. Top with chicken, onion, jalapeno.',
    'Bake 425°F for 10 min until crispy and melted.',
    'Cut into 4 slices.',
  ],
  'Chicken Pineapple Fried Rice': [
    'Dice chicken, season, cook in wok or large skillet.',
    'Scramble 3 eggs in same pan, break into pieces.',
    'Add diced peppers and onion, sauté 3–4 min.',
    'Add cooked rice, pineapple, mixed veggies. Stir-fry together.',
    'Add soy sauce and sugar-free ketchup. Toss to combine.',
    'Distribute into 5 containers.',
  ],
  'Chicken Teriyaki Rice Bowl': [
    'Dice chicken. Season with garlic, ginger, pepper.',
    'Cook chicken in skillet with sesame oil, 5–6 min. Set aside.',
    'Steam or roast broccoli until tender-crisp (~5 min).',
    'Cook rice per package directions.',
    'Toss chicken with teriyaki sauce.',
    'Portion into 4 containers: rice → broccoli → chicken.',
  ],
  'Macro Friendly Big Mac': [
    'Form 200g beef into patty. Season with salt and pepper.',
    'Cook on medium-high to desired doneness.',
    'Toast brioche bun.',
    'Mix sauce: mayo + ketchup + relish + mustard + Worcestershire.',
    'Assemble: bun → sauce → patty → cheese → sauce → top bun.',
  ],
  'BBQ Beef Burritos': [
    'Cook beef with salt, pepper, honey BBQ seasoning.',
    'Add diced peppers + BBQ seasoning + jalapenos with juice.',
    'Add drained kidney beans + 100g BBQ sauce. Mix well.',
    'Distribute into 11 wraps. Roll up.',
    'Toast until crispy.',
  ],
  'Ground Turkey Taco Bowl': [
    'Brown turkey with taco seasoning. Drain.',
    'Cook rice per package directions.',
    'Drain and rinse black beans.',
    'Portion into 4 containers: rice → turkey → beans.',
    'Store salsa, cheese, and lettuce separately.',
    'Top with salsa, cheese, lettuce before eating.',
  ],
  'Dump-and-Bake Taco Bowls': [
    'Brown ground turkey with diced bell peppers, onions, and taco seasoning.',
    'Add turkey bone broth instead of water. Simmer until reduced.',
    'In each container, layer: brown rice, onions, black beans, olives, turkey mixture, bone broth.',
    'Top with lite shredded cheese.',
    'Bake covered at 375°F for 25–30 min until rice is cooked and cheese melted.',
    'Top with salsa, sour cream, avocado before eating.',
  ],
  'Honey Chili Chicken & Cauliflower Rice': [
    'Season chicken thighs with onion powder, paprika, pepper, ginger.',
    'Heat oil in large skillet. Cook chicken in batches until golden.',
    'Mix coconut aminos, chicken broth, honey, garlic, and chili flakes for sauce.',
    'Pour sauce over chicken. Simmer 3–5 min until thickened.',
    'Cook cauliflower rice per package directions.',
    'Portion: cauliflower rice → chicken with sauce. Top with green onions.',
  ],
  'High-Protein Pizza Pasta Bake': [
    'Cook protein pasta per package directions. Drain.',
    'Mix pasta with marinara sauce and seasonings.',
    'Layer into greased baking dish.',
    'Divide into six containers. Top with chopped string cheese, mozzarella, turkey pepperoni, and extra seasoning.',
    'Bake for 20–25 min. Broil for 2 min for a crispy top.',
  ],
  'Creamy Lemon Chicken Orzo': [
    'Season chicken with salt, pepper, garlic, oregano.',
    'Sear chicken in olive oil over medium-high heat, 4–5 minutes per side until golden and cooked through. Remove and set aside.',
    'In same pan, add onion and cook 2–3 minutes until softened, then add garlic for 30 seconds.',
    'Toast dry orzo in the pan for 1 minute to lightly brown.',
    'Pour in chicken broth, bring to a gentle simmer, and cook 8–10 minutes, stirring occasionally, until orzo is tender and creamy.',
    'Lower heat and stir in Greek yogurt, lemon zest, lemon juice, and Parmesan until smooth.',
    'Add spinach. Fold in and let it wilt into the orzo.',
    'Nestle chicken back into the pan and simmer 2–3 minutes to warm through and absorb flavor.',
  ],
  'Steak & Onion Stir Fry': [
    'Marinate beef with all marinade ingredients 20–30 min.',
    'Stir fry onions + mushrooms 3–4 min → set aside.',
    'Cook beef in batches; add garlic when almost done.',
    'Deglaze with rice wine, add sauce ingredients.',
    'Mix ½ tsp arrowroot + 1 tbsp water → stir in off heat till glossy.',
    'Add veggies + green onion tops → toss, season, serve.',
  ],
  'Protein Mac & Cheese Bake': [
    'Cook protein pasta. Drain.',
    'Brown turkey with oil, garlic, and mushrooms. Season generously.',
    'Make meat sauce: add diced tomatoes, sun-dried tomatoes, Rao’s, and basil. Simmer 10 min.',
    'Make cheese sauce: blend cottage cheese, shredded cheese, almond milk, seasonings, arrowroot slurry. Stir into pasta.',
    'Layer in baking dish: pasta cheese mixture → meat sauce → mozzarella & string cheese.',
    'Bake at 375°F for 25–30 min. Broil 2 min for crispy top.',
  ],
  'Fully Loaded Fried Cabbage': [
    'Prep everything — chop peppers, onion, cabbage, bacon, slice sausage.',
    'Heat 1–2 tbsp oil in large pot over medium heat. Add turkey bacon and sausage. Cook until browned. Remove and set aside.',
    'Add shrimp to same pot. Season with garlic powder, onion powder, pepper, Cajun. Cook 1–2 min per side until just pink. Remove and set aside.',
    'Add more oil if needed. Add onion until translucent. Add bell peppers, minced garlic, pepper, Cajun. Stir well.',
    'Add cabbage in batches so it wilts evenly. Do not cover. Season as it cooks.',
    'Return turkey bacon, sausage, and shrimp to pot. Toss until combined and heated through.',
    'Serve hot.',
  ],
  'Chocolate Chip Skillet Cookie': [
    'Mix dry: flour, protein, coconut flour, powdered PB, monkfruit, baking soda.',
    'Add wet: egg whites, applesauce, Greek yogurt. Combine until just mixed.',
    'Press into greased oven-safe skillet. Top with chocolate chips.',
    'Bake at 350°F for 8–10 min.',
  ],
  'Dubai Chocolate Skillet Cookie': [
    'Mix dry: flour, chocolate protein, coconut flour, powdered PB, cocoa, monkfruit, baking soda.',
    'Add wet: egg whites, applesauce, Greek yogurt. Combine.',
    'Press half the dough into skillet. Add melted chocolate in center. Cover with remaining dough.',
    'Bake at 350°F for 10–12 min.',
    'Top with pistachio crème and shredded puff pastry.',
  ],
  'Brookie Skillet': [
    'Make cookie base: mix vanilla protein, coconut flour, margarine, monkfruit, baking powder, vanilla. Press into bottom of skillet. Add chips.',
    'Make brownie layer: mix chocolate protein, flour, coconut flour, cocoa, baking powder. Add almond milk, margarine, yogurt. Pour over cookie base. Top with chips.',
    'Bake at 350°F for 12 min.',
  ],
  'Sugar Cookie Dough': [
    'Mix oat flour, protein, pudding mix, powdered PB, monkfruit, salt.',
    'Add vanilla, yogurt, and almond milk. Stir until cookie dough consistency.',
    'Fold in sprinkles.',
    'Melt white chocolate with coconut oil. Drizzle on top as magic shell.',
    'Refrigerate 30 min+ before eating.',
  ],
  'Red Velvet Cookie Dough': [
    'Mix oat flour, protein, pudding mix, powdered PB, monkfruit, salt.',
    'Add red velvet extract, yogurt, and almond milk. Stir until cookie dough consistency.',
    'Melt chocolate with coconut oil. Drizzle on top as magic shell.',
    'Refrigerate 30 min+ before eating.',
  ],
  'Mini Pumpkin Pie': [
    'Mix Graham cracker crumbs with melted margarine. Press into ramekin or mini pie dish.',
    'Blend all filling ingredients until smooth.',
    'Pour filling over crust.',
    'Bake at 350°F for 40 min until set.',
    'Cool completely before serving.',
  ],
  'Biscoff Tiramisu': [
    'Mix yogurt, ricotta, protein powder, cornstarch, vanilla, and monkfruit until smooth.',
    'Dip Biscoff cookies briefly in espresso/coffee.',
    'Layer in a jar or bowl: soaked cookies → cream mixture → repeat.',
    'Top with crushed Biscoff cookies.',
    'Refrigerate 3+ hours (overnight is best).',
  ],
  "Chicken & Fries with Cane's Sauce": [
    'Season chicken with salt, pepper, paprika, garlic powder, sea salt.',
    'Cook chicken (grill, skillet, or bake at 400°F until 165°F internal).',
    'Air fry sweet potato fries per package directions.',
    "Mix all Cane's sauce ingredients together (Greek yogurt, light mayo, sugar-free ketchup, honey mustard, Worcestershire).",
    'Slice chicken, toss with hot honey.',
    'Divide everything into 4 meal preps.',
  ],
  'Protein Overnight Oats': [
    'Combine oats, almond milk, yogurt, protein, chia seeds, and sweetener in a jar or container.',
    'Stir well until fully mixed.',
    'Cover and refrigerate overnight (or at least 4 hours).',
    'In the morning, stir again, add desired toppings, and enjoy cold.',
    'Keeps in fridge for up to 4 days — great for batch prep.',
  ],
  // ---------- budget mains (2026-07-23 batch) ----------
  'Buffalo Chicken Bowls with Cauliflower Garlic Rice': [
    'Marinate: combine chicken, hot sauce, honey, garlic powder, paprika, salt, onion powder, and pepper in a bag. Refrigerate 30 minutes to 2 hours.',
    'Rice: cook white rice per package directions.',
    'Cauliflower: spread cauliflower rice on a sheet pan, drizzle with olive oil and salt. Roast at 425°F for 20–30 min until browned. Stir into the cooked rice.',
    'Chicken: heat a grill pan over high heat. Cook marinated chicken a few minutes per side until browned and cooked through. Rest, then slice.',
    'Assemble: divide rice and chicken into 4 containers. Pack cucumber, tomato, and dill dip or ranch separately.',
  ],
  'Creamy Lobster Bisque Pasta': [
    'Thaw the langostino tails in a colander under cold water for 3–5 minutes. Pat dry and season with salt and pepper.',
    'Sear the langostino: heat butter in a skillet over medium heat. Add garlic and stir until melted into the butter. Add the langostino tails and cook 2–3 minutes in the garlic butter sauce.',
    'Cook the pasta per package directions, then drain.',
    'Combine: return the drained pasta to the pot and pour in the lobster bisque. Stir to coat evenly.',
    'Finish and serve: add the langostino tails along with the remaining garlic butter from the skillet. Heat through 1–2 minutes. Plate and top with grated Parmesan and chopped parsley if desired.',
  ],
  'Creamy Gochujang Noodles with Sesame Beef': [
    'Boil and blend: bring a large pot of water to a boil. Blend low-fat cottage cheese, gochujang, and water until smooth. Set aside.',
    'Mix the beef sauce: stir together sauce packets, maple syrup, coconut aminos or low-sodium soy sauce, rice vinegar, and the white parts of the sliced green onions. Set aside.',
    'Cook the beef: brown the ground beef in a pan over medium-high heat until fully cooked. Pour in the sauce and stir. Let it sit untouched 2–3 minutes so it thickens and caramelizes on the bottom.',
    'Cook the noodles: once the sauce hits the beef, drop the noodles into the boiling water and cook per package directions (about 4 minutes). Reserve some pasta water, then drain.',
    'Toss and serve: add the drained noodles to the pot with the blended gochujang sauce. Toss together, splashing in reserved pasta water as needed to loosen the sauce. Top with the crispy beef, green onion tops, and toasted sesame seeds.',
  ],
  'Marry Me Chicken Pasta': [
    'Cook the protein pasta in salted boiling water until al dente. Reserve ½ cup pasta water, then drain.',
    'Season & sear the chicken: pat dry, season with salt & pepper. Sear in olive oil over medium-high heat until golden and cooked through, about 4 minutes per side. Remove and set aside.',
    'Prepare the sauce: in the same skillet, melt butter, sauté garlic ~30 seconds until fragrant. Stir in sun-dried tomatoes and tomato paste. Pour in chicken broth and bring to a simmer.',
    'Make it creamy: lower heat, stir in the light cream, Parmesan, Italian seasoning, and paprika. Stir until smooth and slightly thickened.',
    'Combine everything: return the chicken to the skillet along with the cooked pasta. Toss gently to coat. Add reserved pasta water a little at a time if the sauce is too thick.',
    'Garnish & serve: sprinkle fresh basil (or parsley) on top and extra Parmesan if desired. Serve immediately.',
  ],
  'Chicken Bacon Ranch Pasta Salad': [
    'Cook the bacon in a large pan over low heat until crispy. Set aside, reserving about 2 tablespoons of drippings in the pan.',
    'Cook the chicken: rub diced chicken with olive oil and season with poultry or Italian seasoning. Cook in the same skillet over medium-low heat 3–4 minutes per side until golden and fully cooked.',
    'Cook the pasta: while the chicken cooks, bring a large pot of salted water to a boil and cook pasta per package directions. Drain and rinse under cool water.',
    'Assemble the salad base: in a large mixing bowl, combine the cooked pasta, chicken, bacon, cheddar cheese, and green onions. Pour in most of the ranch dressing (reserve a little) and toss well to coat. Add seasoning to taste.',
    'Finish and serve: just before serving, add shredded romaine lettuce, croutons, and the remaining dressing. Toss lightly to combine.',
  ],
  'Garlic Butter Chicken Meatballs with Cauliflower Rice': [
    'Cauliflower rice: grate cauliflower or use pre-riced. Add to a plate with water, cover, and microwave about 4 minutes.',
    'Mix meatballs: combine ground chicken, cheese, grated garlic, Italian seasoning, bouillon, chili flakes, parsley, and pepper. Form into medium balls.',
    'Cook meatballs: melt butter in a skillet over medium-low heat. Cook meatballs 8–10 minutes, turning and basting, until browned and cooked through. Set aside.',
    'Sauce: in the same skillet, melt remaining butter. Add lemon juice, stock, hot sauce, minced garlic, parsley, and red pepper flakes. Simmer 3–4 minutes until slightly reduced. Season to taste.',
    'Assemble: divide cauliflower rice into containers, top with meatballs, drizzle with sauce or pack sauce separately.',
  ],
  'Marry Me Shrimp Pasta': [
    'Cook the pasta in salted boiling water until al dente. Reserve ½ cup pasta water, then drain.',
    'Prepare the shrimp: pat dry, season lightly with smoked paprika and garlic salt. Set aside.',
    'Cook the guanciale (or olive oil substitute): heat a large skillet over medium heat until crispy, about 5–6 minutes. Remove and set aside, leaving the rendered fat in the pan.',
    'Sauté the aromatics: add onion and cook 2–3 minutes until softened. Stir in garlic and cook 30 seconds until fragrant.',
    'Build the sauce: add smoked paprika, Italian seasoning, dried parsley, and cayenne. Stir 30 seconds to bloom the spices. Pour in the heavy cream and bring to a gentle simmer. Stir in Parmesan until melted and smooth. Season with salt and pepper.',
    'Cook the shrimp: add shrimp to the skillet and cook 2 minutes per side, or until pink and cooked through. Return the guanciale to the sauce.',
    'Combine with pasta: add the cooked pasta to the skillet, tossing well to coat. Add reserved pasta water as needed to loosen the sauce.',
    'Serve: divide into plates and garnish with fresh parsley. Serve immediately.',
  ],
  'Crispy Honey-Garlic Chicken with Rice': [
    'Coat the chicken: pat dry, season with salt and pepper, then toss with potato starch until evenly coated.',
    'Air-fry the chicken: preheat air fryer to 390°F. Lightly spray the basket with olive oil. Air fry chicken 12–14 minutes, shaking halfway, until golden and crisp.',
    'Cook the vegetables: in a skillet over medium-high heat, add a splash of olive oil, sliced carrot, and green pepper chunks. Stir-fry 3–4 minutes until slightly softened.',
    'Make the honey-garlic sauce: add honey, soy sauce, rice vinegar, minced garlic, grated ginger, chili flakes, and chicken broth directly into the skillet with the vegetables. Bring to a simmer.',
    'Thicken the sauce: add the potato starch + water slurry and stir until the sauce thickens and becomes glossy.',
    'Combine chicken and sauce: add the crispy air-fried chicken to the skillet and toss until fully coated in the sticky honey-garlic glaze and veggies.',
    'Cook the noodles: in another pan, heat sesame oil, add julienned carrot and white parts of green onion. Stir-fry 2 minutes. Add cooked noodles, soy sauce, garlic powder, black pepper, and green onion tops. Toss 1–2 minutes.',
    'Plate the meal: serve the honey-garlic chicken and vegetables over jasmine rice, with the stir-fried noodles on the side.',
  ],
  // ---------- cheesecake bowls — shared no-cook method ----------
  'Cookies & Cream Cheesecake Bowl': [
    'Mix all ingredients together until smooth.',
    'Store in the fridge for 3+ hours to set.',
    'Top with a crushed Oreo before eating.',
  ],
  'Biscoff Cheesecake Bowl': [
    'Mix all ingredients together until smooth.',
    'Store in the fridge for 3+ hours to set.',
    'Top with a crushed Biscoff cookie and a drizzle of Biscoff before eating.',
  ],
  'Strawberry Shortcake Cheesecake': [
    'Mix all ingredients together until smooth.',
    'Store in the fridge for 3+ hours to set.',
    'Top with strawberries and a crushed vanilla wafer before eating.',
  ],
}