// AUTO-GENERATED from The-Menu.html cookbook (2026-07-23). Step-by-step cooking
// directions per recipe, matched by exact name against lib/recipes.ts. Only recipes
// that actually need directions are covered here — simple grab-and-go snacks (e.g.
// "Banana + Nut Butter") don't have a directions section in the source doc.
export const RECIPE_INSTRUCTIONS: Record<string, string[]> = {
  'Chicken Nugget Hash Brown Bake': [
    'Mix all base ingredients in a 13 oz oven-safe container.',
    'Bake at 375°F for 30 min until eggs are cooked through.',
    'Add cheese on top and heat again until melted.',
    'Top with pico and enjoy.',
  ],
  'Beef & Egg Breakfast Power Bowl': [
    'Season beef with paprika, garlic, onion, pepper, salt. Brown in large skillet. Drain.',
    'Chop bacon into small pieces. Cook until crispy.',
    'Scramble eggs with all-purpose seasoning.',
    'Spread potatoes on sheet pan. Spray with oil. Bake 400°F for 20 min. Broil 500°F for 10 min.',
    'Combine all ingredients. Mix evenly.',
    'Weigh total. Divide by 10. Portion into 10 containers.',
  ],
  'Steak, Egg & Cheese Breakfast Bagels': [
    'Cook steak to 125°F internal. Rest 5 min. Slice thin.',
    'Cook bacon until crispy.',
    'Cook eggs your way.',
    'Toast Sola protein bagels.',
    'Assemble: bagel → steak → bacon → egg → cheese → top.',
    'Wrap in foil for storage.',
  ],
  'Turkey Sausage Sweet Potato Hash': [
    'Dice sweet potatoes. Toss with cooking spray. Roast at 400°F for 20 min.',
    'Season turkey with paprika, garlic, salt, pepper. Brown in large skillet. Drain.',
    'Chop bacon into small pieces. Cook until crispy.',
    'Sauté peppers & onion 3–4 min.',
    'Combine all ingredients. Mix evenly.',
    'Portion into 4 containers.',
  ],
  'BBQ Chicken Pizza': [
    'Season chicken with Italian, salt, red pepper. Cook 3–5 min per side (160°F+).',
    'Dice chicken.',
    'Spread BBQ sauce on pizza crust.',
    'Add cheese evenly. Top with chicken, onion, jalapeno.',
    'Bake 425°F for 10 min until crispy and melted.',
    'Cut into 4 slices.',
  ],
  'Chicken Pineapple Fried Rice': [
    'Dice chicken, season, cook in wok or large skillet.',
    'Scramble 3 eggs in same pan, break into pieces.',
    'Add diced peppers and onion, sauté 3–4 min.',
    'Add cooked rice, pineapple, mixed veggies. Stir-fry together.',
    'Add soy sauce and sugar-free ketchup. Toss to combine.',
    'Distribute into 5 containers.',
  ],
  'Chicken Teriyaki Rice Bowl': [
    'Dice chicken. Season with garlic, ginger, pepper.',
    'Cook chicken in skillet with sesame oil, 5–6 min. Set aside.',
    'Steam or roast broccoli until tender-crisp (~5 min).',
    'Cook rice per package directions.',
    'Toss chicken with teriyaki sauce.',
    'Portion into 4 containers: rice → broccoli → chicken.',
  ],
  'Macro Friendly Big Mac': [
    'Form 200g beef into patty. Season with salt and pepper.',
    'Cook on medium-high to desired doneness.',
    'Toast brioche bun.',
    'Mix sauce: mayo + ketchup + relish + mustard + Worcestershire.',
    'Assemble: bun → sauce → patty → cheese → sauce → top bun.',
  ],
  'BBQ Beef Burritos': [
    'Cook beef with salt, pepper, honey BBQ seasoning.',
    'Add diced peppers + BBQ seasoning + jalapenos with juice.',
    'Add drained kidney beans + 100g BBQ sauce. Mix well.',
    'Distribute into 11 wraps. Roll up.',
    'Toast until crispy.',
  ],
  'Ground Turkey Taco Bowl': [
    'Brown turkey with taco seasoning. Drain.',
    'Cook rice per package directions.',
    'Drain and rinse black beans.',
    'Portion into 4 containers: rice → turkey → beans.',
    'Store salsa, cheese, and lettuce separately.',
    'Top with salsa, cheese, lettuce before eating.',
  ],
  'Dump-and-Bake Taco Bowls': [
    'Brown ground turkey with diced bell peppers, onions, and taco seasoning.',
    'Add turkey bone broth instead of water. Simmer until reduced.',
    'In each container, layer: brown rice, onions, black beans, olives, turkey mixture, bone broth.',
    'Top with lite shredded cheese.',
    'Bake covered at 375°F for 25–30 min until rice is cooked and cheese melted.',
    'Top with salsa, sour cream, avocado before eating.',
  ],
  'Honey Chili Chicken & Cauliflower Rice': [
    'Season chicken thighs with onion powder, paprika, pepper, ginger.',
    'Heat oil in large skillet. Cook chicken in batches until golden.',
    'Mix coconut aminos, chicken broth, honey, garlic, and chili flakes for sauce.',
    'Pour sauce over chicken. Simmer 3–5 min until thickened.',
    'Cook cauliflower rice per package directions.',
    'Portion: cauliflower rice → chicken with sauce. Top with green onions.',
  ],
  'High-Protein Pizza Pasta Bake': [
    'Cook protein pasta per package directions. Drain.',
    'Mix pasta with marinara sauce and seasonings.',
    'Layer into greased baking dish.',
    'Divide into six containers. Top with chopped string cheese, mozzarella, turkey pepperoni, and extra seasoning.',
    'Bake for 20–25 min. Broil for 2 min for a crispy top.',
  ],
  'Creamy Lemon Chicken Orzo': [
    'Season chicken with salt, pepper, garlic, oregano.',
    'Sear chicken in olive oil over medium-high heat, 4–5 minutes per side until golden and cooked through. Remove and set aside.',
    'In same pan, add onion and cook 2–3 minutes until softened, then add garlic for 30 seconds.',
    'Toast dry orzo in the pan for 1 minute to lightly brown.',
    'Pour in chicken broth, bring to a gentle simmer, and cook 8–10 minutes, stirring occasionally, until orzo is tender and creamy.',
    'Lower heat and stir in Greek yogurt, lemon zest, lemon juice, and Parmesan until smooth.',
    'Add spinach. Fold in and let it wilt into the orzo.',
    'Nestle chicken back into the pan and simmer 2–3 minutes to warm through and absorb flavor.',
  ],
  'Steak & Onion Stir Fry': [
    'Marinate beef with all marinade ingredients 20–30 min.',
    'Stir fry onions + mushrooms 3–4 min → set aside.',
    'Cook beef in batches; add garlic when almost done.',
    'Deglaze with rice wine, add sauce ingredients.',
    'Mix ½ tsp arrowroot + 1 tbsp water → stir in off heat till glossy.',
    'Add veggies + green onion tops → toss, season, serve.',
  ],
  'Protein Mac & Cheese Bake': [
    'Cook protein pasta. Drain.',
    'Brown turkey with oil, garlic, and mushrooms. Season generously.',
    'Make meat sauce: add diced tomatoes, sun-dried tomatoes, Rao’s, and basil. Simmer 10 min.',
    'Make cheese sauce: blend cottage cheese, shredded cheese, almond milk, seasonings, arrowroot slurry. Stir into pasta.',
    'Layer in baking dish: pasta cheese mixture → meat sauce → mozzarella & string cheese.',
    'Bake at 375°F for 25–30 min. Broil 2 min for crispy top.',
  ],
  'Fully Loaded Fried Cabbage': [
    'Prep everything — chop peppers, onion, cabbage, bacon, slice sausage.',
    'Heat 1–2 tbsp oil in large pot over medium heat. Add turkey bacon and sausage. Cook until browned. Remove and set aside.',
    'Add shrimp to same pot. Season with garlic powder, onion powder, pepper, Cajun. Cook 1–2 min per side until just pink. Remove and set aside.',
    'Add more oil if needed. Add onion until translucent. Add bell peppers, minced garlic, pepper, Cajun. Stir well.',
    'Add cabbage in batches so it wilts evenly. Do not cover. Season as it cooks.',
    'Return turkey bacon, sausage, and shrimp to pot. Toss until combined and heated through.',
    'Serve hot.',
  ],
  'Chocolate Chip Skillet Cookie': [
    'Mix dry: flour, protein, coconut flour, powdered PB, monkfruit, baking soda.',
    'Add wet: egg whites, applesauce, Greek yogurt. Combine until just mixed.',
    'Press into greased oven-safe skillet. Top with chocolate chips.',
    'Bake at 350°F for 8–10 min.',
  ],
  'Dubai Chocolate Skillet Cookie': [
    'Mix dry: flour, chocolate protein, coconut flour, powdered PB, cocoa, monkfruit, baking soda.',
    'Add wet: egg whites, applesauce, Greek yogurt. Combine.',
    'Press half the dough into skillet. Add melted chocolate in center. Cover with remaining dough.',
    'Bake at 350°F for 10–12 min.',
    'Top with pistachio crème and shredded puff pastry.',
  ],
  'Brookie Skillet': [
    'Make cookie base: mix vanilla protein, coconut flour, margarine, monkfruit, baking powder, vanilla. Press into bottom of skillet. Add chips.',
    'Make brownie layer: mix chocolate protein, flour, coconut flour, cocoa, baking powder. Add almond milk, margarine, yogurt. Pour over cookie base. Top with chips.',
    'Bake at 350°F for 12 min.',
  ],
  'Sugar Cookie Dough': [
    'Mix oat flour, protein, pudding mix, powdered PB, monkfruit, salt.',
    'Add vanilla, yogurt, and almond milk. Stir until cookie dough consistency.',
    'Fold in sprinkles.',
    'Melt white chocolate with coconut oil. Drizzle on top as magic shell.',
    'Refrigerate 30 min+ before eating.',
  ],
  'Red Velvet Cookie Dough': [
    'Mix oat flour, protein, pudding mix, powdered PB, monkfruit, salt.',
    'Add red velvet extract, yogurt, and almond milk. Stir until cookie dough consistency.',
    'Melt chocolate with coconut oil. Drizzle on top as magic shell.',
    'Refrigerate 30 min+ before eating.',
  ],
  'Mini Pumpkin Pie': [
    'Mix Graham cracker crumbs with melted margarine. Press into ramekin or mini pie dish.',
    'Blend all filling ingredients until smooth.',
    'Pour filling over crust.',
    'Bake at 350°F for 40 min until set.',
    'Cool completely before serving.',
  ],
  'Biscoff Tiramisu': [
    'Mix yogurt, ricotta, protein powder, cornstarch, vanilla, and monkfruit until smooth.',
    'Dip Biscoff cookies briefly in espresso/coffee.',
    'Layer in a jar or bowl: soaked cookies → cream mixture → repeat.',
    'Top with crushed Biscoff cookies.',
    'Refrigerate 3+ hours (overnight is best).',
  ],
}